version: '3.8'

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: dockerfile
    image: gateway
    container_name: gateway
    ports:
      - '3001:3001'
    depends_on:
      - rabbitmq
    volumes:
      - ./gateway/src:/usr/src/app/src

  microservice:
    build:
      context: ./microservice
      dockerfile: dockerfile
    image: microservice
    container_name: microservice
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - '15672:15672'
      - '5672:5672'
